services:
  app:
    container_name: to_do_list_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:cached               # Codebase
      - laravel_vendor:/var/www/html/vendor  # Persistent vendor
      - laravel_storage:/var/www/html/storage # Persistent storage
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - laravel
    working_dir: /var/www/html

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - laravel

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - .:/var/www/html:cached
    depends_on:
      - app
    networks:
      - laravel

  node:
    container_name: to_do_list_node
    image: node:20-alpine
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:cached
    networks:
      - laravel
    command: sh -c "npm install && npm run dev"

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
  laravel_vendor:
  laravel_storage:
